server:
  port: 8081
spring:
  application:
    name: test_demo_core
  redis:
    database: 0
    host: 127.0.0.1
    timeout: 5000

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test_demo?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    name: test_demo
    username: root
    password: password
  flyway:
    enabled: true
    out-of-order: true

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml