server:
  port: 8080
spring:
  application:
    name: gateway_test
  cloud:
    gateway:
      enabled: true
      routes:
        - id: baidu_route
          uri: http://www.baidu.com
          predicates:
            - Path=/baidu/**
        - id: test_demo
          uri: http://localhost:8081
          order: 1
          predicates:
            - Path=/test_demo/**
        - id: test_feignClient
          uri: http://localhost:8082
          order: 1
          predicates:
            - Path=/feignClient/**